services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '8081:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - /mnt/data_lake/logs/traefik:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dash.rule=Host(`traefik.rmmservice.co.za`)"
      - "traefik.http.routers.traefik-dash.entrypoints=web"
      - "traefik.http.routers.traefik-dash.service=api@internal"
      - "traefik.http.routers.traefik-dash.middlewares=authelia@docker"
    networks:
      - netlock_netlock-network

networks:
  netlock_netlock-network:
    external: true
