api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ':80'
    proxyProtocol:
      trustedIPs:
        - 127.0.0.1
        - 192.168.50.239
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1
        - 192.168.50.239
  websecure:
    address: ':443'

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    network: netlock_netlock-network
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

accessLog:
  filePath: '/var/log/traefik/access.log'
  bufferingSize: 100

serversTransport:
  insecureSkipVerify: true
