services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${NETLOCK_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: "w7cdks"
    volumes:
      - /home/netlock/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      netlock-network:
    restart: always
    command:
      - --skip-log-bin
      - --innodb_buffer_pool_size=1G
      - --innodb_log_file_size=256M
      - --innodb_flush_log_at_trx_commit=2
      - --max_connections=200

  netlock-rmm-web-console:
    image: nicomak101/netlock-rmm-web-console:latest
    container_name: netlock-rmm-web-console
    user: root
    environment:
      - TZ=Africa/Johannesburg
      - ASPNETCORE_URLS=http://+:80
      - Kestrel__Http=true
      - Kestrel__Https=false
      - Kestrel__Https_Force=false
      - Kestrel__CustomCertificatePath=/app/certificates/cortex_dummy.pfx
      - Kestrel__CustomCertificatePassword=dummy
    volumes:
      - '/home/netlock/web_console/appsettings.json:/app/appsettings.json'
      - '/home/netlock/web_console/internal:/app/internal'
      - '/home/netlock/web_console/logs:/var/0x101 Cyber Security/NetLock RMM/Web Console/'
      - '/home/netlock/certificates:/app/certificates'
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.netlock-console.rule=Host(`rmm.rmmservice.co.za`)'
      - 'traefik.http.routers.netlock-console.entrypoints=web'
      - 'traefik.http.routers.netlock-console.middlewares=authelia@docker'
      - 'traefik.http.services.netlock-console.loadbalancer.server.port=80'
    networks:
      netlock-network:
    restart: always
    depends_on:
      - mysql

  netlock-rmm-server:
    image: nicomak101/netlock-rmm-server:latest
    container_name: netlock-rmm-server
    environment:
      - TZ=Africa/Johannesburg
      - ASPNETCORE_URLS=http://+:80
      - Kestrel__Http=true
      - Kestrel__Https=false
      - Kestrel__Https_Force=false
      - Kestrel__CustomCertificatePath=/app/certificates/cortex_dummy.pfx
      - Kestrel__CustomCertificatePassword=dummy
      - MembersPortalApi__ApiKeyOverride=764286af-438b-4f83-b4ed-b4936a45c853-71090d1d-73e4-43dd-908c-b8777fd54465
      - MembersPortal__ApiKey=764286af-438b-4f83-b4ed-b4936a45c853-71090d1d-73e4-43dd-908c-b8777fd54465
      - MembersPortal__SkipSync=true
    volumes:
      - '/home/netlock/server/appsettings.json:/app/appsettings.json'
      - '/home/netlock/server/internal:/app/internal'
      - '/home/netlock/server/files:/app/www/private/files'
      - '/home/netlock/server/logs:/var/0x101 Cyber Security/NetLock RMM/Server/'
      - '/home/netlock/certificates:/app/certificates'
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '7080:7080'
      - '7081:7081'
    networks:
      netlock-network:
    restart: always
    depends_on:
      - mysql

networks:
  netlock-network:
    external: true
    name: netlock_netlock-network

